/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PresentationsRouteRouteImport } from './routes/presentations/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthPatRouteImport } from './routes/auth/pat'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PresentationsSlugRouteImport } from './routes/presentations/$slug'
import { Route as PresentationsCatalogRouteImport } from './routes/presentations/catalog'
import { Route as PresentationsShowcaseRouteImport } from './routes/presentations/showcase'
import { Route as PresentationsUploadRouteImport } from './routes/presentations/upload'
import { Route as RegistryIndexRouteImport } from './routes/registry/index'
import { Route as RegistryNameRouteImport } from './routes/registry/$name'
import { Route as RegistryUploadRouteImport } from './routes/registry/upload'
import { Route as ScopesIndexRouteImport } from './routes/scopes/index'
import { Route as ScopesScopeRouteImport } from './routes/scopes/$scope'
import { Route as RegistryNameVersionRouteImport } from './routes/registry/$name.$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRouteRoute = PresentationsRouteRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPatRoute = AuthPatRouteImport.update({
  id: '/auth/pat',
  path: '/auth/pat',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsSlugRoute = PresentationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsCatalogRoute = PresentationsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsShowcaseRoute = PresentationsShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsUploadRoute = PresentationsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryNameRoute = RegistryNameRouteImport.update({
  id: '/registry/$name',
  path: '/registry/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryUploadRoute = RegistryUploadRouteImport.update({
  id: '/registry/upload',
  path: '/registry/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopesIndexRoute = ScopesIndexRouteImport.update({
  id: '/scopes/',
  path: '/scopes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopesScopeRoute = ScopesScopeRouteImport.update({
  id: '/scopes/$scope',
  path: '/scopes/$scope',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryNameVersionRoute = RegistryNameVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => RegistryNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/pat': typeof AuthPatRoute
  '/presentations/$slug': typeof PresentationsSlugRoute
  '/presentations/catalog': typeof PresentationsCatalogRoute
  '/presentations/showcase': typeof PresentationsShowcaseRoute
  '/presentations/upload': typeof PresentationsUploadRoute
  '/registry/$name': typeof RegistryNameRouteWithChildren
  '/registry/upload': typeof RegistryUploadRoute
  '/scopes/$scope': typeof ScopesScopeRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/scopes/': typeof ScopesIndexRoute
  '/registry/$name/$version': typeof RegistryNameVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/pat': typeof AuthPatRoute
  '/presentations/$slug': typeof PresentationsSlugRoute
  '/presentations/catalog': typeof PresentationsCatalogRoute
  '/presentations/showcase': typeof PresentationsShowcaseRoute
  '/presentations/upload': typeof PresentationsUploadRoute
  '/registry/$name': typeof RegistryNameRouteWithChildren
  '/registry/upload': typeof RegistryUploadRoute
  '/scopes/$scope': typeof ScopesScopeRoute
  '/presentations': typeof PresentationsIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/scopes': typeof ScopesIndexRoute
  '/registry/$name/$version': typeof RegistryNameVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/pat': typeof AuthPatRoute
  '/presentations/$slug': typeof PresentationsSlugRoute
  '/presentations/catalog': typeof PresentationsCatalogRoute
  '/presentations/showcase': typeof PresentationsShowcaseRoute
  '/presentations/upload': typeof PresentationsUploadRoute
  '/registry/$name': typeof RegistryNameRouteWithChildren
  '/registry/upload': typeof RegistryUploadRoute
  '/scopes/$scope': typeof ScopesScopeRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/scopes/': typeof ScopesIndexRoute
  '/registry/$name/$version': typeof RegistryNameVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presentations'
    | '/admin'
    | '/dashboard'
    | '/auth/login'
    | '/auth/me'
    | '/auth/pat'
    | '/presentations/$slug'
    | '/presentations/catalog'
    | '/presentations/showcase'
    | '/presentations/upload'
    | '/registry/$name'
    | '/registry/upload'
    | '/scopes/$scope'
    | '/presentations/'
    | '/registry/'
    | '/scopes/'
    | '/registry/$name/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/auth/login'
    | '/auth/me'
    | '/auth/pat'
    | '/presentations/$slug'
    | '/presentations/catalog'
    | '/presentations/showcase'
    | '/presentations/upload'
    | '/registry/$name'
    | '/registry/upload'
    | '/scopes/$scope'
    | '/presentations'
    | '/registry'
    | '/scopes'
    | '/registry/$name/$version'
  id:
    | '__root__'
    | '/'
    | '/presentations'
    | '/admin'
    | '/dashboard'
    | '/auth/login'
    | '/auth/me'
    | '/auth/pat'
    | '/presentations/$slug'
    | '/presentations/catalog'
    | '/presentations/showcase'
    | '/presentations/upload'
    | '/registry/$name'
    | '/registry/upload'
    | '/scopes/$scope'
    | '/presentations/'
    | '/registry/'
    | '/scopes/'
    | '/registry/$name/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresentationsRouteRoute: typeof PresentationsRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMeRoute: typeof AuthMeRoute
  AuthPatRoute: typeof AuthPatRoute
  RegistryNameRoute: typeof RegistryNameRouteWithChildren
  RegistryUploadRoute: typeof RegistryUploadRoute
  ScopesScopeRoute: typeof ScopesScopeRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  ScopesIndexRoute: typeof ScopesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pat': {
      id: '/auth/pat'
      path: '/auth/pat'
      fullPath: '/auth/pat'
      preLoaderRoute: typeof AuthPatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/$slug': {
      id: '/presentations/$slug'
      path: '/$slug'
      fullPath: '/presentations/$slug'
      preLoaderRoute: typeof PresentationsSlugRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/catalog': {
      id: '/presentations/catalog'
      path: '/catalog'
      fullPath: '/presentations/catalog'
      preLoaderRoute: typeof PresentationsCatalogRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/showcase': {
      id: '/presentations/showcase'
      path: '/showcase'
      fullPath: '/presentations/showcase'
      preLoaderRoute: typeof PresentationsShowcaseRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/upload': {
      id: '/presentations/upload'
      path: '/upload'
      fullPath: '/presentations/upload'
      preLoaderRoute: typeof PresentationsUploadRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name': {
      id: '/registry/$name'
      path: '/registry/$name'
      fullPath: '/registry/$name'
      preLoaderRoute: typeof RegistryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/upload': {
      id: '/registry/upload'
      path: '/registry/upload'
      fullPath: '/registry/upload'
      preLoaderRoute: typeof RegistryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scopes/': {
      id: '/scopes/'
      path: '/scopes'
      fullPath: '/scopes/'
      preLoaderRoute: typeof ScopesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scopes/$scope': {
      id: '/scopes/$scope'
      path: '/scopes/$scope'
      fullPath: '/scopes/$scope'
      preLoaderRoute: typeof ScopesScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name/$version': {
      id: '/registry/$name/$version'
      path: '/$version'
      fullPath: '/registry/$name/$version'
      preLoaderRoute: typeof RegistryNameVersionRouteImport
      parentRoute: typeof RegistryNameRoute
    }
  }
}

interface PresentationsRouteRouteChildren {
  PresentationsSlugRoute: typeof PresentationsSlugRoute
  PresentationsCatalogRoute: typeof PresentationsCatalogRoute
  PresentationsShowcaseRoute: typeof PresentationsShowcaseRoute
  PresentationsUploadRoute: typeof PresentationsUploadRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

const PresentationsRouteRouteChildren: PresentationsRouteRouteChildren = {
  PresentationsSlugRoute: PresentationsSlugRoute,
  PresentationsCatalogRoute: PresentationsCatalogRoute,
  PresentationsShowcaseRoute: PresentationsShowcaseRoute,
  PresentationsUploadRoute: PresentationsUploadRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}

const PresentationsRouteRouteWithChildren =
  PresentationsRouteRoute._addFileChildren(PresentationsRouteRouteChildren)

interface RegistryNameRouteChildren {
  RegistryNameVersionRoute: typeof RegistryNameVersionRoute
}

const RegistryNameRouteChildren: RegistryNameRouteChildren = {
  RegistryNameVersionRoute: RegistryNameVersionRoute,
}

const RegistryNameRouteWithChildren = RegistryNameRoute._addFileChildren(
  RegistryNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresentationsRouteRoute: PresentationsRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMeRoute: AuthMeRoute,
  AuthPatRoute: AuthPatRoute,
  RegistryNameRoute: RegistryNameRouteWithChildren,
  RegistryUploadRoute: RegistryUploadRoute,
  ScopesScopeRoute: ScopesScopeRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  ScopesIndexRoute: ScopesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
