http:
  routers:
    registry:
      rule: "PathPrefix(`/api/registry`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - registry-strip
      service: registry-service

    auth:
      rule: "PathPrefix(`/api/auth`) || Path(`/.well-known/jwks.json`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - auth-strip
      service: auth-service

    website:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      priority: 1
      service: website-service

  middlewares:
    registry-strip:
      stripPrefix:
        prefixes:
          - /api/registry
        forceSlash: false

    auth-strip:
      stripPrefix:
        prefixes:
          - /api/auth
        forceSlash: false

  services:
    registry-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3001"

    auth-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"

    website-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3100"
